spring:
  application:
    name: users

  datasource:
    url: jdbc:mysql://localhost:3306/users_malucos
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 9090
  servlet:
    context-path: api/v1/users # Ruta de contexto de todo el proyecto

security:
  jwt:
    secret-key: ${env.jwt.secret-key} # Genera con openssl rand -base64 32
    token-expiration: ${env.jwt.token-expiration} # 10 min expresado en milisegundos